services:
  backend:
    build:
      context: ./backend/larabelproject
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend/larabelproject:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres_sample
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: postgres_sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
